version: "3.8"
services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./startup.sh:/usr/share/elasticsearch/startup.sh

volumes:
  esdata:
    driver: local